// Package planner turns a validated request into an explicit execution plan.
//
// The plan is where ambiguity disappears: resolved targets, ordered steps,
// execution strategy. Nothing in execution should have to re-derive scope.
package planner

import (
	"fmt"
	"sort"
	"strings"

	"github.com/webdobe/dploy/internal/config"
	"github.com/webdobe/dploy/internal/environment"
	"github.com/webdobe/dploy/internal/operation"
)

// Plan is the materialized operation ready to execute.
type Plan struct {
	Operation   operation.Type
	Environment string
	Class       string
	Strategy    config.Strategy
	Targets     []TargetPlan
	Artifact    string
}

// TargetPlan is the per-target slice of a Plan.
//
// Env, if non-empty, is merged onto os.Environ() by LocalRunner before
// each step runs. Sync operations use this to expose DPLOY_SOURCE,
// DPLOY_TARGET, etc. to script-first sync workflows.
type TargetPlan struct {
	Name  string
	Type  string
	Host  string
	Path  string
	Roles []string
	Env   map[string]string
	Steps []Step
}

// Step is one ordered command scheduled against a target.
type Step struct {
	Index   int
	Command string
}

// BuildDeploy expands a deploy Request against resolved env/config into a Plan.
func BuildDeploy(req operation.Request, cfg *config.Config, resolved *environment.Resolved) (*Plan, error) {
	envCfg := cfg.Environments[resolved.Name]
	return build(operation.TypeDeploy, envCfg.Deploy, req, resolved)
}

// BuildRollback expands a rollback Request against resolved env/config into a Plan.
// Returns an error if the environment has no rollback block defined —
// rollback is an explicit recovery operation, not an implicit inverse of deploy.
func BuildRollback(req operation.Request, cfg *config.Config, resolved *environment.Resolved) (*Plan, error) {
	envCfg := cfg.Environments[resolved.Name]
	if len(envCfg.Rollback) == 0 {
		return nil, fmt.Errorf("environment %q has no rollback steps defined", resolved.Name)
	}
	return build(operation.TypeRollback, envCfg.Rollback, req, resolved)
}

// BuildSync builds a sync Plan from source → target for the requested
// resource(s). For v1, sync is script-first and runs locally: the plan
// has a single "local" target that runs the concatenated workflow
// commands from source.data.<resource> in order. Source/target env
// names and classes are exposed to scripts via environment variables.
//
// The workflow name is the resource name (e.g. "database") looked up
// in the source environment's data: block.
func BuildSync(req operation.Request, cfg *config.Config, source, target *environment.Resolved) (*Plan, error) {
	if req.SourceEnv == "" || req.TargetEnv == "" {
		return nil, fmt.Errorf("sync requires both source and target environments")
	}
	if len(req.Resources) == 0 {
		return nil, fmt.Errorf("sync requires at least one resource")
	}

	sourceEnv := cfg.Environments[source.Name]

	// Concatenate workflow steps for each requested resource, preserving
	// both order of resources and order within each workflow.
	var plannedSteps []Step
	idx := 0
	for _, res := range req.Resources {
		wf, ok := sourceEnv.Data[res]
		if !ok {
			available := sortedDataKeys(sourceEnv.Data)
			if len(available) == 0 {
				return nil, fmt.Errorf("source environment %q has no data: workflows defined", source.Name)
			}
			return nil, fmt.Errorf("source environment %q has no data.%s workflow (available: %s)", source.Name, res, strings.Join(available, ", "))
		}
		for _, cmd := range wf {
			plannedSteps = append(plannedSteps, Step{Index: idx, Command: cmd})
			idx++
		}
	}

	env := map[string]string{
		"DPLOY_SOURCE":       source.Name,
		"DPLOY_TARGET":       target.Name,
		"DPLOY_SOURCE_CLASS": source.Class,
		"DPLOY_TARGET_CLASS": target.Class,
		"DPLOY_RESOURCES":    strings.Join(req.Resources, ","),
	}

	return &Plan{
		Operation: operation.TypeSync,
		// State is keyed by Environment; for sync, that's the target
		// (the env whose data changed). SourceEnv/TargetEnv on the
		// Result carry the full picture for audit.
		Environment: target.Name,
		Class:       target.Class,
		Artifact:    req.Artifact,
		Targets: []TargetPlan{
			{
				Name:  "local",
				Type:  "local",
				Path:  ".",
				Env:   env,
				Steps: plannedSteps,
			},
		},
	}, nil
}

// BuildCapture builds a capture Plan for the named environment. Capture
// is single-env (unlike sync), runs locally, and produces a snapshot
// metadata record alongside the normal state record.
//
// snapshotID is generated by the caller (from the operation's start
// time) and plumbed into the plan as DPLOY_SNAPSHOT_ID so scripts can
// use it to tag their outputs.
//
// The workflow name is the resource name looked up in the source
// environment's capture: block.
func BuildCapture(req operation.Request, cfg *config.Config, source *environment.Resolved, snapshotID string) (*Plan, error) {
	if source == nil {
		return nil, fmt.Errorf("capture requires a resolved environment")
	}
	if len(req.Resources) == 0 {
		return nil, fmt.Errorf("capture requires at least one resource")
	}
	if snapshotID == "" {
		return nil, fmt.Errorf("capture requires a snapshot id")
	}

	sourceEnv := cfg.Environments[source.Name]

	var plannedSteps []Step
	idx := 0
	for _, res := range req.Resources {
		wf, ok := sourceEnv.Capture[res]
		if !ok {
			available := sortedDataKeys(sourceEnv.Capture)
			if len(available) == 0 {
				return nil, fmt.Errorf("environment %q has no capture: workflows defined", source.Name)
			}
			return nil, fmt.Errorf("environment %q has no capture.%s workflow (available: %s)", source.Name, res, strings.Join(available, ", "))
		}
		for _, cmd := range wf {
			plannedSteps = append(plannedSteps, Step{Index: idx, Command: cmd})
			idx++
		}
	}

	env := map[string]string{
		"DPLOY_SOURCE":       source.Name,
		"DPLOY_SOURCE_CLASS": source.Class,
		"DPLOY_RESOURCES":    strings.Join(req.Resources, ","),
		"DPLOY_SNAPSHOT_ID":  snapshotID,
	}

	return &Plan{
		Operation:   operation.TypeCapture,
		Environment: source.Name,
		Class:       source.Class,
		Targets: []TargetPlan{
			{
				Name:  "local",
				Type:  "local",
				Path:  ".",
				Env:   env,
				Steps: plannedSteps,
			},
		},
	}, nil
}

// sortedDataKeys returns the keys of m in sorted order. Used only to
// produce a deterministic "available workflows" list in error messages.
func sortedDataKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// build is the shared core of BuildDeploy / BuildRollback. opType labels
// the plan for audit; steps is the ordered step list to expand against
// each resolved target under on/on_role filters and --targets scoping.
func build(opType operation.Type, steps []config.Step, req operation.Request, resolved *environment.Resolved) (*Plan, error) {
	p := &Plan{
		Operation:   opType,
		Environment: resolved.Name,
		Class:       resolved.Class,
		Strategy:    resolved.Strategy,
		Artifact:    req.Artifact,
	}

	targets := resolved.Targets
	if len(req.Targets) > 0 {
		targets = environment.FilterByName(targets, req.Targets)
		if len(targets) == 0 {
			return nil, fmt.Errorf("no targets match requested names %v", req.Targets)
		}
	}

	for _, t := range targets {
		tp := TargetPlan{
			Name:  t.Name,
			Type:  t.Type,
			Host:  t.Host,
			Path:  t.Path,
			Roles: append([]string(nil), t.Roles...),
		}

		for i, step := range steps {
			if !stepMatches(step, t) {
				continue
			}
			tp.Steps = append(tp.Steps, Step{
				Index:   i,
				Command: step.Run,
			})
		}

		if len(tp.Steps) > 0 {
			p.Targets = append(p.Targets, tp)
		}
	}

	if len(p.Targets) == 0 {
		return nil, fmt.Errorf("plan has no executable steps against any target")
	}

	return p, nil
}

// stepMatches returns true if the step's on/on_role filters include the target.
// A step with no filters applies to all targets.
func stepMatches(step config.Step, t environment.Target) bool {
	if step.OnRole != "" {
		found := false
		for _, r := range t.Roles {
			if r == step.OnRole {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	if len(step.On) > 0 {
		for _, name := range step.On {
			if name == t.Name {
				return true
			}
		}
		return false
	}
	return true
}
